"""Sphinx configuration."""

import sys
from pathlib import Path
from typing import Any


project = "Invoice2data"
author = "Manuel Riel"
copyright = "2024, Manuel Riel"

# import invoice2data

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# sys.path.insert(0, os.path.abspath('..'))

# Insert invoice2data's path into the system.
sys.path.insert(0, str(Path("../src").resolve()))

extensions = [
    "sphinxmermaid",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx_click",
    "myst_parser",
    # Converts the README's remote SVG badges to PDF so the LaTeX/PDF builder
    # can embed them (needs the rsvg-convert binary from librsvg2-bin, which
    # Read the Docs installs via build.apt_packages in .readthedocs.yaml).
    "sphinxcontrib.rsvgconverter",
]
autodoc_typehints = "description"
html_theme = "shibuya"
myst_fence_as_directive = ["mermaid"]


html_logo = "_static/logo.png"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.ico"


def setup(app: Any) -> None:
    """Skip mermaid diagrams in non-HTML builders.

    The sphinxmermaid extension only registers an HTML visitor for its
    MermaidNode, so builders like LaTeX/PDF crash with "unknown node type:
    MermaidNode". The diagrams are rendered client-side by mermaid.js and
    cannot be drawn in those outputs anyway, so render nothing for them.
    """
    from docutils import nodes
    from sphinxmermaid import MermaidNode

    def skip_mermaid(self: Any, node: Any) -> None:
        raise nodes.SkipNode

    app.add_node(
        MermaidNode,
        override=True,
        latex=(skip_mermaid, None),
        text=(skip_mermaid, None),
        man=(skip_mermaid, None),
        texinfo=(skip_mermaid, None),
    )
