"""Sphinx configuration."""

import os
import sys


project = "Invoice2data"
author = "Manuel Riel"
copyright = "2024, Manuel Riel"

# import invoice2data

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# sys.path.insert(0, os.path.abspath('..'))

# Insert invoice2data's path into the system.
sys.path.insert(0, os.path.abspath("../src"))

extensions = [
    "sphinxmermaid",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx_click",
    "myst_parser",
]
autodoc_typehints = "description"
html_theme = "furo"
myst_fence_as_directive = ["mermaid"]


html_logo = "_static/logo.png"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.ico"
